# Deprecated in v1.16 in favor of apiextensions.k8s.io/v1
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: cwalerts.crd.k8s.sas.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: crd.k8s.sas.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: cwalerts
    # singular name to be used as an alias on the CLI and for display
    singular: cwalert
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CloudWatchMetricAlarm
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - cwa
  # preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            AlarmName:
              type: string
              # minLength: 1
              # maxLenght: 255
            ComparisonOperator:
              type: string
              pattern: 'GreaterThanOrEqualToThreshold|GreaterThanThreshold|LessThanThreshold|LessThanOrEqualToThreshold|LessThanLowerOrGreaterThanUpperThreshold|LessThanLowerThreshold|GreaterThanUpperThreshold'
            EvaluationPeriods:
              type: integer
              minimum: 1
            MetricName:
              type: string
              # minLength: 1
              # maxLenght: 255
            Namespace:
              type: string
              # minLength: 1
              # maxLenght: 255
              pattern: '[^:].*'              
            Period:
              type: integer
              minimum: 1              
            Statistic:
              type: string
              pattern: 'SampleCount|Average|Sum|Minimum|Maximum'
            Threshold:
              type: number
              format: double
            InsufficientDataActions:
              type: array
              items: 
                 type: string
            AlarmDescription:
              type: string
              # default: "Created by cwalerts.sas.io CRD"
            AlarmActions:
              type: array
              items:
                 type: string
            OKActions:
              type: array
              items:
                 type: string
            TreatMissingData:
               type: string
              #  default: "notBreaching"
            Tags:
               type: array
               items:
                type: object
               properties:
                Key:
                  type: string
                Value:
                  type: string
            Dimensions:
               type: array
               items:
                 type: object
               properties:
                 Name:
                   type: string
                 Value: 
                   type: string
            Unit:
               type: string
               pattern: 'Seconds|Microseconds|Milliseconds|Bytes|Kilobytes|Megabytes|Gigabytes|Terabytes|Bits|Kilobits|Megabits|Gigabits|Terabits|Percent|Count|Bytes\/Second|Kilobytes\/Second|Megabytes\/Second|Gigabytes\/Second|Terabytes\/Second|Bits\/Second|Kilobits\/Second|Megabits\/Second|Gigabits\/Second|Terabits\/Second|Count\/Second|None'      
      # required:
      #   - MetricName
     