---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloudwatch-alerts-operator
  name: cloudwatch-alerts-operator
rules:
  - apiGroups:
      - ""
      - crd.k8s.sas.io
      - apiextensions.k8s.io      
      - extensions
      - events.k8s.io
      - events
    resources:
      - customresourcedefinitions
      - clusterkopfpeerings
      - cwalerts
      - events
      # - ingresses
      # - ingresses/status
      # - services
      # - pods/status
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: cloudwatch-alerts-operator
  name: cloudwatch-alerts-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudwatch-alerts-operator
subjects:
  - kind: ServiceAccount
    name: cloudwatch-alerts-operator
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: cloudwatch-alerts-operator
  name: cloudwatch-alerts-operator
  namespace: kube-system